### ISSUE TITLE
Hardware Requirements: Flexible? 

### ISSUE THREAD

**Issue by kianrafiee** [parisbutterfield/restswitchmate#2]
Hi @parisbutterfield ! 

I am excited to try out your code. I was trying to use the official Switchmate Power Outlet to act as a hub for my Switchmate Toggle Switches but it just does not work. It's a complete mess and the company seems like they don't have a clue at the moment.

Anyway, I have a Raspberry Pi 3 Model B that I have Pi-Hole running on and thought I'd use it for restswitchmate as well.

So I was wondering, is there any flexibility with the hardware requirements? Can I use my Pi 3? 

Also, can I use an external USB hub? Like [this one](https://www.amazon.com/Anker-4-Port-Macbook-Surface-Notebook/dp/B00XMD7KPU/ref=sr_1_3?s=electronics&ie=UTF8&qid=1520496763&sr=1-3&keywords=usb+hub) and just hook it up to a usb port on the Pi 3 and have the bluetooth adapters hooked up to the USB hub?

And can I use [this](https://www.bestbuy.com/site/insignia-bluetooth-4-0-usb-adapter-black/4884001.p?skuId=4884001) usb bluetooth adapter?

Thank you so much for your work on this project. I'm not sure why it doesn't have more exposure(or does it?) because I found it on a reddit thread. Believe me if this works for me you saved me some bucks and a lot of headaches.

**Comment by parisbutterfield** [comment]
Hey @kianrafiee !
The hardware requirements are pretty flexible. The Pi Zero W I used is just an example.

You can definitely use the Pi 3. 

You should be able to use any external USB hub. I'd caution against using a USB 3.0 hub because of the [interference between bluetooth and USB 3](https://www.intel.com/content/www/us/en/io/universal-serial-bus/usb3-frequency-interference-paper.html). When I was developing on my Mac (Mac -> USB 3 Hub -> USB Bluetooth adapter) I noticed really bad interference. Shouldn't happen on the Pi, but I'd plug directly into the Pi first.

I can't find much about that Bluetooth adapter. I would buy one from this list https://elinux.org/RPi_USB_Bluetooth_adapters

And thank you for the kind words. Hope to get you up and running soon.

**Comment by kianrafiee** [comment]
Awesome. Issue resolved.
